[alias]
lint = "clippy --all-targets --all-features -- -D warnings"
lint-fix = "clippy --all-targets --all-features --fix --allow-dirty -- -D warnings"
fmt-check = "fmt --all -- --check"

[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
